# Generated by Django 4.0.5 on 2022-07-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0004_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Maculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
